changelog:
  exclude:
    labels:
      - duplicate
      - wontfix
  categories:
    - title: Docs
      labels:
        - documentation
    - title: Fixes
      labels:
        - bug
    - title: Features
      labels:
        - enhancement
    - title: Other changes
      labels:
        - "*"
